import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>SG Class of 2024!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <div className={styles.container}>
          <p className={styles.thank}>THANK YOU</p>
          <p className={styles.thank}>SG Class of 2024</p>
        </div>
        <div className="cartoon hb">
          <div className="sky r"></div>
          <div className="cloud cloud-1 ha"></div>
          <div className="cloud cloud-2 ha"></div>
          <div className="shadow"></div>
          <div className="minar-top minar-top-2"></div>
          <div className="minar-top"></div>
          <div className="minar ha"></div>
          <div className="tower tower-5 tower-6 tower-7"></div>
          <div className="house ha"></div>
          <div className="main-roof-behind"></div>
          <div className="main-roof ha"></div>
          <div className="main-top"></div>
          <div className="flag flag-4"></div>
          <div className="main-tower-roof"></div>
          <div className="main-tower"></div>
          <div className="main ha"></div>
          <div className="tower tower-3 tower-3a"></div>
          <div className="wall ha"></div>
          <div className="tower tower-1"></div>
          <div className="tower tower-2"></div>
          <div className="tower tower-3 tower-3b"></div>
          <div className="tower tower-4"></div>
          <div className="tower tower-5 tower-6"></div>
          <div className="tower tower-5"></div>
          <div className="brick"></div>
          <div className="room-1"></div>
          <div className="room-2"></div>
          <div className="room-3 ha"></div>
          <div className="window"></div>
          <div className="window-curved"></div>
          <div className="roof roof-1"></div>
          <div className="roof roof-2"></div>
          <div className="flag flag-1"></div>
          <div className="flag flag-2"></div>
          <div className="flag flag-3"></div>
          <div className="flag-pole-top"></div>
          <div className="flag-pole"></div>
          <div className="house-roof"></div>
          <div className="front-gate ha">
            <div className="gate"></div>
            <div className="balcony ha"></div>
            <div className="triangle ha"></div>
            <div className="front-poles"></div>
          </div>
        </div>
        <p className={styles.name}>By Avril Cui</p>
      </main>
    </>
  );
}
